# Generated by Django 4.2 on 2023-05-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('titoloCompilation', models.CharField(max_length=1000)),
                ('descrizioneCompilation', models.TextField()),
                ('nomeGiocatore', models.CharField(blank=True, max_length=100)),
                ('squadra', models.CharField(blank=True, max_length=100)),
                ('giornata', models.CharField(blank=True, max_length=100)),
                ('competizione', models.CharField(blank=True, choices=[('Serie A', 'Serie A'), ('Serie B', 'Serie B'), ('Champions League', 'Champions League'), ('Mondiali 2006', 'Mondiali 2006'), ('Coppa Italia', 'Coppa Italia'), ('Eredivise', 'Eredivise'), ('Europa League', 'Europa League')], max_length=100)),
                ('descrizioneGoal', models.CharField(blank=True, choices=[('Testa', 'Testa'), ('Rigore', 'Rigore'), ('Al volo', 'Al volo'), ('GDM', 'GDM'), ('Tiro da fuori', 'Tiro da fuori'), ('Tiro in area', 'Tiro in area'), ('Punizione', 'Punizione'), ('Dribling sul portiere', 'Dribling sul portiere'), ('Pallonetto', 'Pallonetto'), ('Autogol', 'Autogol')], max_length=500)),
                ('stagione', models.CharField(blank=True, choices=[('2022/2023', '2022/2023'), ('2021/2022', '2021/2022'), ('2006/2007', '2006/2007'), ('2001/2002', '2001/2002')], max_length=100)),
                ('valutazione', models.CharField(blank=True, choices=[('1 stella', '1 stella'), ('2 stelle', '2 stelle'), ('3 stelle', '3 stelle'), ('4 stelle', '4 stelle'), ('5 stelle', '5 stelle')], max_length=100)),
                ('dataFrom', models.CharField(blank=True, default='0000-00-00', max_length=100)),
                ('dataTo', models.CharField(blank=True, default='0000-00-00', max_length=100)),
            ],
            options={
                'unique_together': {('titoloCompilation',)},
            },
        ),
    ]
