# Generated by Django 4.2 on 2023-05-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='dataFrom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='dataTo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
