# Generated by Django 4.2 on 2023-05-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilations', '0003_alter_compilation_competizione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='competizione',
            field=models.CharField(blank=True, choices=[('Serie A', 'Serie A'), ('Serie B', 'Serie B'), ('Champions League', 'Champions League'), ('Mondiali 2006', 'Mondiali 2006'), ('Coppa Italia', 'Coppa Italia'), ('Eredivise', 'Eredivise'), ('Europa League', 'Europa League')], max_length=100),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='dataFrom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='dataTo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='descrizioneGoal',
            field=models.CharField(blank=True, choices=[('Testa', 'Testa'), ('Rigore', 'Rigore'), ('Al volo', 'Al volo'), ('GDM', 'GDM'), ('Tiro da fuori', 'Tiro da fuori'), ('Tiro in area', 'Tiro in area'), ('Punizione', 'Punizione'), ('Dribling sul portiere', 'Dribling sul portiere'), ('Pallonetto', 'Pallonetto'), ('Autogol', 'Autogol')], max_length=500),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='giornata',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='nomeGiocatore',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='squadra',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='stagione',
            field=models.CharField(blank=True, choices=[('2022/2023', '2022/2023'), ('2021/2022', '2021/2022'), ('2006/2007', '2006/2007'), ('2001/2002', '2001/2002')], max_length=100),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='valutazione',
            field=models.CharField(blank=True, choices=[('1 stella', '1 stella'), ('2 stelle', '2 stelle'), ('3 stelle', '3 stelle'), ('4 stelle', '4 stelle'), ('5 stelle', '5 stelle')], max_length=100),
        ),
    ]
