# Generated by Django 4.2 on 2023-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilations', '0005_alter_compilation_stagione'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
