# Generated by Django 4.2 on 2023-05-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilations', '0006_compilation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
