# Generated by Django 4.2 on 2023-05-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compilations', '0007_alter_compilation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilation',
            name='slug',
        ),
    ]
