# Generated by Django 4.2 on 2023-04-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gols', '0003_alter_gol_ora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gol',
            name='competizione',
            field=models.CharField(choices=[('Serie A', 'Serie A'), ('Serie B', 'Serie B'), ('Champions League', 'Champions League'), ('Mondiali 2006', 'Mondiali 2006'), ('Coppa Italia', 'Coppa Italia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='gol',
            name='descrizioneGoal',
            field=models.CharField(choices=[('Testa', 'Testa'), ('Rigore', 'Rigore'), ('Al volo', 'Al volo'), ('GDM', 'GDM'), ('Tiro da fuori', 'Tiro da fuori'), ('Tiro in area', 'Tiro in area'), ('Punizione', 'Punizione'), ('Dribling sul portiere', 'Dribling sul portiere')], max_length=500),
        ),
        migrations.AlterField(
            model_name='gol',
            name='giornata',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gol',
            name='nomeGiocatore',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gol',
            name='partita',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gol',
            name='squadra',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gol',
            name='stagione',
            field=models.CharField(choices=[('2022/2023', '2022/2023'), ('2021/2022', '2021/2022'), ('2006/2007', '2006/2007')], max_length=100),
        ),
        migrations.AlterField(
            model_name='gol',
            name='valutazione',
            field=models.CharField(choices=[('1 stella', '1 stella'), ('2 stelle', '2 stelle'), ('3 stelle', '3 stelle'), ('4 stelle', '4 stelle'), ('5 stelle', '5 stelle')], max_length=100),
        ),
        migrations.AlterField(
            model_name='gol',
            name='video',
            field=models.CharField(max_length=5000),
        ),
    ]
