# Generated by Django 4.2 on 2023-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gols', '0004_alter_gol_competizione_alter_gol_descrizionegoal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gol',
            name='competizione',
            field=models.CharField(choices=[('Serie A', 'Serie A'), ('Serie B', 'Serie B'), ('Champions League', 'Champions League'), ('Mondiali 2006', 'Mondiali 2006'), ('Coppa Italia', 'Coppa Italia'), ('Eredivise', 'Eredivise')], max_length=100),
        ),
    ]
