# Generated by Django 4.2 on 2023-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gols', '0005_alter_gol_competizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gol',
            name='stagione',
            field=models.CharField(choices=[('2022/2023', '2022/2023'), ('2021/2022', '2021/2022'), ('2006/2007', '2006/2007'), ('2001/2002', '2001/2002')], max_length=100),
        ),
    ]
