# Generated by Django 4.2 on 2023-05-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gols', '0008_alter_gol_descrizionegoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gol',
            name='descrizioneGoal',
            field=models.CharField(choices=[('Testa', 'Testa'), ('Rigore', 'Rigore'), ('Al volo', 'Al volo'), ('GDM', 'GDM'), ('Tiro da fuori', 'Tiro da fuori'), ('Tiro in area', 'Tiro in area'), ('Punizione', 'Punizione'), ('Dribling sul portiere', 'Dribling sul portiere'), ('Pallonetto', 'Pallonetto'), ('Autogol', 'Autogol')], max_length=500),
        ),
    ]
